### ISSUE TITLE
Why is this so awesome?

### ISSUE THREAD

**Issue by mcanthony** [alexose/window.js#1]
and yet seems to have caught no attention... This tool is exactly what I planned to make (some day in the never) and is what a lot of people need. It amazes me it never caught on. If your interested in collaborating (or not) I intend to modernize it using CSS3 warez and reactive fluffery, build some basic theme options within a build script which can allow you to pre-configure the desired layout and spit out only the css/markup/js needed. I would likely make it a component, with the JS module split in two parts, the core module for the interaction, and the ability for it to be composable/persistent during runtime (for flexible apps). This way it's a tool and a component for building and builders...

Let me know if your interested in making such a thing I could use the moral support. I would like to make something like the golden layout engine but with more liberal licensing and capabilities demonstrated here.

I would also like to extend it or make a plugin for it, which would allow for basic panel styles to be added (for native-ish apps) which can be purposed to be much like photoshop panels, optionally with tabs support.

**Comment by alexose** [comment]
Hi, @mcanthony!  

Thank you for the kind words.  I would agree that there is more potential here, and I would of course welcome any contributions towards that front.

And sorry for the slow response-- It turns out I wasn't watching my notifications closely enough :)
